# Generated by Django 3.1 on 2020-08-15 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isGeneral', models.BooleanField()),
                ('isQuestion', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=1000)),
                ('start_time', models.IntegerField(validators=[django.core.validators.MinLengthValidator(0)])),
                ('end_time', models.IntegerField(validators=[django.core.validators.MinLengthValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
