# Generated by Django 3.1 on 2020-08-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='end_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='start_time',
            field=models.PositiveIntegerField(),
        ),
    ]
